jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t dabsquared/go:$TAG .
